# Generated by Django 6.0 on 2026-01-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('kind', models.CharField(max_length=50, verbose_name='종류')),
                ('content', models.TextField(verbose_name='설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ideas/', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SWIDEA_SITE.devtool', verbose_name='예상 개발툴')),
            ],
        ),
    ]
