# Generated by Django 5.2.4 on 2026-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calorie',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=3, verbose_name='칼로리'),
        ),
        migrations.AddField(
            model_name='post',
            name='carbo',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=3, verbose_name='탄수화물'),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=3, verbose_name='지방'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.CharField(default='기타', max_length=20, verbose_name='해시태그'),
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_img',
            field=models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='영양성분이미지'),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=100.0, max_digits=3, verbose_name='단백질'),
        ),
    ]
