# Generated by Django 5.2.4 on 2026-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_calorie_post_carbo_post_fat_post_hashtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nutrition_img',
        ),
        migrations.AddField(
            model_name='post',
            name='nutrition_image',
            field=models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='영양성분 이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.CharField(default='기타', max_length=20, verbose_name='상품 종류 해시태그'),
        ),
    ]
