# Generated by Django 6.0.1 on 2026-01-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='포스터 경로(TMDB)')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='포스터 이미지(직접 업로드)')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='개봉년도')),
                ('genre', models.CharField(blank=True, choices=[('ACTION', '액션'), ('ROMANCE', '로맨스/멜로'), ('SF', 'SF'), ('THRILLER', '스릴러'), ('DRAMA', '드라마')], max_length=50, null=True, verbose_name='장르')),
                ('director', models.CharField(blank=True, max_length=100, null=True, verbose_name='감독')),
                ('actors', models.CharField(blank=True, help_text=',로 구분', max_length=500, null=True, verbose_name='주연배우')),
                ('running_time', models.IntegerField(blank=True, null=True, verbose_name='러닝타임(분)')),
                ('tmdb_average', models.FloatField(default=0.0, verbose_name='TMDB 평점')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], default=5, verbose_name='별점')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_tmdb', models.BooleanField(default=False, verbose_name='TMDB 출처 여부')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MovieChatBot.movie', verbose_name='영화')),
            ],
        ),
    ]
