# Generated by Django 6.0 on 2025-12-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='release_date',
            new_name='release_year',
        ),
    ]
