# Generated by Django 6.0 on 2025-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
