# Generated by Django 6.0 on 2025-12-31 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovieReviews', '0004_review_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='actors',
            field=models.CharField(max_length=200, verbose_name='주연'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='리뷰 내용'),
        ),
        migrations.AlterField(
            model_name='review',
            name='director',
            field=models.CharField(max_length=100, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('ACTION', '액션'), ('ROMANCE', '로맨스'), ('COMEDY', '코미디'), ('THRILLER', '스릴러'), ('DRAMA', '드라마'), ('SF', 'SF')], max_length=100, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='review',
            name='release_year',
            field=models.IntegerField(verbose_name='개봉년도'),
        ),
        migrations.AlterField(
            model_name='review',
            name='running_time',
            field=models.IntegerField(verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
